QualityCapsIrina/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace QualityCapsIrina.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers/Profile/5
        public ActionResult Profile(int id)
        {
            return View();
        }

        // GET: Customers/Create
        public ActionResult Orders()
        {
            return View();
        }        
    }
}

QualityCapsIrina/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityCapsIrina.Data;
using QualityCapsIrina.Models;
using QualityCapsIrina.Models.ViewModels;

namespace QualityCapsIrina.Controllers
{
    public class ItemsController : Controller
    {
        private readonly StoreContext _context;

        public ItemsController(StoreContext context)
        {
            _context = context;
        }

        // GET: Items
        [Route("[controller]/men")]
        [Route("[controller]/women")]
        public async Task<IActionResult> Shop(
            double minPrice,
            double maxPrice,
            int category,
            string searchQuery,
            int? page,
            int pageSize = 6,
            SortOrder sortOrder = SortOrder.Name)
        {
            string genderString = Request.Path.Value.Split('/')[2].ToLower();
            Gender gender = (genderString == "men") ? Gender.Men : Gender.Women;
            ViewData["Gender"] = gender;    

            var shopViewModel = new ShopViewModel();
            IQueryable<Item> items = _context.Items
                .Where(item => (item.Gender == gender) || (item.Gender == Gender.Unisex))
                .Include(i => i.Category).Include(i => i.Supplier);

            //category filtering
            ViewData["ActiveCategory"] = category;
            if (category != 0)
            {
                items = items.Where(i => i.CategoryId == category);
            }

            //price filtering  
            var interimItemList = items.ToList();
            ViewData["MinScalePrice"] = interimItemList.Min(i => i.Price);
            ViewData["MinPrice"] = (minPrice != 0) ? minPrice : ViewData["MinScalePrice"];
            ViewData["MaxScalePrice"] = interimItemList.Max(i => i.Price);
            ViewData["MaxPrice"] = (maxPrice != 0) ? maxPrice : ViewData["MaxScalePrice"];

            if (minPrice != 0)
            {
                items = items.Where(i => i.Price >= minPrice);
            }
            if (maxPrice != 0)
            {
                items = items.Where(i => i.Price <= maxPrice);
            }

            //string search
            ViewData["SearchQuery"] = searchQuery;
            if (searchQuery != null && searchQuery.Length > 0)
            {
                items = items.Where(i => i.Name.Contains(searchQuery));
            }

            //sorting
            ViewData["SortOrders"] = GenerateSortList(sortOrder);
            ViewData["CurrentSortOrder"] = sortOrder;
            switch (sortOrder)
            {
                case SortOrder.Price:
                    items = items.OrderBy(i => i.Price);
                    break;
                case SortOrder.PriceDesc:
                    items = items.OrderByDescending(i => i.Price);
                    break;
                case SortOrder.NameDesc:
                    items = items.OrderByDescending(i => i.Name);
                    break;
                case SortOrder.Name:
                default:
                    items = items.OrderBy(i => i.Name);
                    break;
            }

            //shopViewModel.items = await items.ToListAsync();
            //pagination
            ViewData["PageSizes"] = new SelectList(new List<int> { 6, 12, 20, 40 }, pageSize);
            ViewData["PageSize"] = pageSize;
            shopViewModel.items = await PaginatedList<Item>.CreateAsync(items.AsNoTracking(), page ?? 1, pageSize);

            shopViewModel.categories = await _context.Categories
                    .Where(x => x.Items.Any<Item>(item => (item.Gender == gender) || (item.Gender == Gender.Unisex)))
                    .ToListAsync();
            shopViewModel.categories.Add(new Category { CategoryId = 0, Name = "All" });

            return View(shopViewModel);
        }
        
        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.Category)
                .Include(i => i.Supplier)
                .SingleOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }
        
        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ItemId == id);
        }
        private List<SelectListItem> GenerateSortList(SortOrder selected)
        {
            var sortList = new List<SelectListItem>();
            foreach (SortOrder v in Enum.GetValues(typeof(SortOrder)))
            {
                sortList.Add(new SelectListItem
                {
                    Text = v.GetDescription(),
                    Value = v.ToString(),
                    Selected = (v == selected)
                });
            }
            return sortList;
        }
    }
}

QualityCapsIrina/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using QualityCapsIrina.Data;
using QualityCapsIrina.Models;


namespace QualityCapsIrina.Controllers
{    
    public class OrdersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly StoreContext _context;
        private readonly ShoppingCart _shoppingCart;

        public OrdersController(StoreContext context, ShoppingCart shoppingCart, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _shoppingCart = shoppingCart;
            _userManager = userManager;
        }

        // GET: Orders
        //public async Task<IActionResult> Index()
        //{
        //    var storeContext = _context.Orders.Include(o => o.Customer);
        //    return View(await storeContext.ToListAsync());
        //}

        //// GET: Orders/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var order = await _context.Orders
        //        .Include(o => o.Customer)
        //        .SingleOrDefaultAsync(m => m.OrderID == id);
        //    if (order == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(order);
        //}

        // GET: Orders/Checkout
        public async Task<IActionResult> CheckOut(int step = 1)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account", new { returnUrl = $"/Orders/Checkout?step={step}" });

            if (!User.IsInRole("customer"))
            {
                TempData["Message"] = "Only customers can make orders";
                TempData["Title"] = "Error";
                return RedirectToAction("Index", "Home");
            }       
           
            if (step==1)
            {
                return RedirectToAction(nameof(ConfirmDetails));
            }
            else if (step==2)
            {
                var items = _shoppingCart.GetShoppingCartItems();
                _shoppingCart.ShoppingCartItems = items;
                var _order = new Order
                {
                    Status = OrderStatus.Waiting,
                    Date = DateTime.Now,
                    Subtotal = (double)_shoppingCart.GetShoppingCartTotal(),
                    GST = 15,
                    GrandTotal = Math.Round((double)_shoppingCart.GetShoppingCartTotal() * 1.15, 2),
                    CustomerID = _userManager.GetUserId(User)
                };

                if (ModelState.IsValid)
                {
                    _order.OrderItems = new List<OrderItem>();
                    foreach (var item in _shoppingCart.ShoppingCartItems)
                    {
                        var orderItem = new OrderItem
                        {
                            ItemID = item.Item.ItemId,
                            Quantity = item.Amount
                        };
                        _context.OrderItems.Add(orderItem);
                        _order.OrderItems.Add(orderItem);
                    }
                    _context.Orders.Add(_order);
                    await _context.SaveChangesAsync();
                    _shoppingCart.ClearCart();
                    return RedirectToAction(nameof(CheckoutComplete));
                    //return View(_order);
                }
            }            
            return RedirectToAction("Error","Home");
        }

        [Authorize]
        public async Task<IActionResult> ConfirmDetails()
        {
            Customer customer = (Customer)(await _userManager.GetUserAsync(User));
            return View(customer);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDetails(
            [Bind("FirstName, LastName, HomeNumber, MobileNumber, WorkNumber, AddressLine1, AddressLine2, City, ZipCode")] Customer submittedCustomer)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    Customer customer = (Customer)(await _userManager.GetUserAsync(User));
                    customer.FirstName = submittedCustomer.FirstName;
                    customer.LastName = submittedCustomer.LastName;
                    customer.HomeNumber = submittedCustomer.HomeNumber;
                    customer.MobileNumber = submittedCustomer.MobileNumber;
                    customer.WorkNumber = submittedCustomer.WorkNumber;
                    customer.AddressLine1 = submittedCustomer.AddressLine1;
                    customer.AddressLine2 = submittedCustomer.AddressLine2;
                    customer.City = submittedCustomer.City;
                    customer.ZipCode = submittedCustomer.ZipCode;                    
                    var result = await _userManager.UpdateAsync(customer);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Checkout", new { step = 2 });
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
                catch (InvalidOperationException e) {
                    return RedirectToAction("Error", "Home");
                }
                
            }
            return View(submittedCustomer);
        }

        // POST: Orders/Checkout
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> CheckOut(Order order)
        //{
        //    var items = _shoppingCart.GetShoppingCartItems();
        //    _shoppingCart.ShoppingCartItems = items;
        //    var _order = new Order
        //    {
        //        Status = OrderStatus.Waiting,
        //        Date = DateTime.Now,
        //        Subtotal = (double)_shoppingCart.GetShoppingCartTotal(),
        //        GST = 15,
        //        GrandTotal = (double)_shoppingCart.GetShoppingCartTotal() * 1.15,
        //        CustomerID = _userManager.GetUserId(User)
        //    };            

        //    if (ModelState.IsValid)
        //    {
        //        foreach (var item in _shoppingCart.ShoppingCartItems)
        //        {
        //            var orderItem = new OrderItem
        //            {
        //                ItemID = item.Item.ItemId,
        //                Quantity = item.Amount
        //            };
        //            _context.Add(orderItem);
        //            _order.OrderItems.Add(orderItem);
        //        }
        //        _context.Add(order);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(CheckOutComplete));
        //    }
            
        //    return View();
        //}        

        // GET: Orders/CheckOutComplete
        public IActionResult CheckoutComplete()
        {
            return View();
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }
    }
}

QualityCapsIrina/Areas/Admin/Views/Shared/ItemList.cshtml
@model IEnumerable<QualityCapsIrina.Models.Item>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <img src="@item.ImageUrl" asp-append-version="true" width="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Supplier.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ItemId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ItemId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ItemId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

QualityCapsIrina/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    string contr = ViewContext.RouteData.Values["Controller"].ToString().ToLower();
    string action = ViewContext.RouteData.Values["Action"].ToString().ToLower();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QualityCapsIrina</title>
    <base href='@Url.Content("~/")' />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/admin.css" />
        <link rel="stylesheet" href="~/css/dropdown.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
              integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/admin.css" />
        <link rel="stylesheet" href="~/css/dropdown.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="nav-main">
        <div class="nav-block nav-logo" style="justify-content: flex-start;">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo-qc.png" alt="logo" />
            </a>
        </div>
        <div class="nav-block nav-header">
            <a asp-area="Admin" asp-controller="Admin" asp-action="Index" style="font-size: 3vw;">Administation panel</a>
        </div>
        <div class="nav-block nav-user-actions">
            <div class="nav-item dropdown">
                <p class="welcome pb-3 pt-3">@User.Identity.Name <i class="fas fa-angle-down"></i></p>
                <div class="dropdown-content dropdown-content-to-right">
                    <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-users"></i> View customer area</a>              
                    <hr class="m-0" />
                    <a asp-area="" asp-controller="Account" asp-action="LogOff"><i class="fas fa-sign-out-alt"></i> Log off</a>
                </div>
            </div>
        </div>
    </nav>
    
    <div class="body-content">
        <div class="page-content-wrapper">
            <ul class="nav nav-tabs mt-3 mb-3 justify-content-center">
                <li class="nav-item">
                    <a class="nav-link @(contr=="categories"? "active" : "")" id="categories-index" asp-area="Admin" asp-controller="Categories" asp-action="Index">
                        <i class="fas fa-sitemap"></i> Categories
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(contr=="items"? "active" : "")" asp-area="Admin" asp-controller="Items" asp-action="Index">
                        <i class="fab fa-pied-piper-hat"></i> Items
</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(contr=="suppliers"? "active" : "")" asp-area="Admin" asp-controller="Suppliers" asp-action="Index">
                        <i class="fas fa-truck"></i> Suppliers
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(contr=="customers"? "active" : "")" asp-area="Admin" asp-controller="Customers" asp-action="Index">
                        <i class="fas fa-users"></i> Customers
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(contr=="orders"? "active" : "")" asp-area="Admin" asp-controller="Orders" asp-action="Index">
                        <i class="fa fa-list-ul"></i> Orders
                    </a>
                </li>
            </ul>
            @RenderBody()
        </div>
        <footer>
            <p>&copy; 2018 - Quality Caps. Administration panel</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/fontawesome-free-5.0.10/svg-with-js/js/fontawesome-all.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"
                asp-fallback-src="~/lib/fontawesome-free-5.0.10/svg-with-js/js/fontawesome-all.min.js"
                crossorigin="anonymous"
                integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>