QualityCapsIrina/ViewComponents/CategoriesListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QualityCapsIrina.Data;
using QualityCapsIrina.Models;

namespace QualityCapsIrina.ViewComponents
{
    public class CategoriesListViewComponent : ViewComponent
    {
        private readonly StoreContext db;
        public CategoriesListViewComponent(StoreContext context)
        {
            db = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(Gender gender)
        {
            var categories = await GetCategoriesAsync(gender);
            return View(categories);
        }
        private Task<List<Category>> GetCategoriesAsync(Gender gender)
        {
            return db.Categories
                    .Where(x => x.Items.Any<Item>(item=>(item.Gender==gender)||(item.Gender == Gender.Unisex)))
                    .ToListAsync();
            
        }
    }
}

QualityCapsIrina/Views/Shared/ShopPageView.cshtml
@model ShopViewModel
<!-- Content page -->
<section class="p-t-55 p-b-65">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-3 pb-4 pr-5">
            <div class="leftbar pr-4 pr-sm-0">
                <h4 class="m-text14 pb-1">
                    Categories
                </h4>

                <ul class="pb-4">
                    @foreach (var category in Model.categories)
                    {
                        <li class="pt-1">
                            <a asp-route-category="@category.CategoryId"
                               class="s-text13 active1 @((ViewData["ActiveCategory"].ToString()==category.CategoryId.ToString())? "active":"")">
                                @category.Name
                            </a>
                        </li>
                    }
                </ul>

                <!--  -->
                <h4 class="m-text14 pb-1">
                    Filters
                </h4>

                <div class="filter-price p-t-22 p-b-50 bo3">
                    <div class="m-text15 p-b-17">
                        Price
                    </div>

                    <div class="slider-range-wrapper">
                        <div id="slider-range"></div>
                    </div>

                    <div class="flex-sb-m flex-w pt-3">
                        <div class="w-size11">
                            <!-- Button -->
                            <button id="filter-price" class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4">
                                Filter
                            </button>
                        </div>
                        <div class="d-flex s-text3 pt-2 pb-2 pl-1">
                            Range: <span style="color:#f6931f; font-weight: bold;">
                                $<span id="value-lower">0</span>
                                - $<span id="value-upper">100</span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="search-product pos-relative bo4 of-hidden">
                    <input class="s-text7 size6 p-l-23 p-r-50"
                           id="search-query"
                           type="text"
                           name="search-product"
                           value="@ViewBag.SearchQuery"
                           placeholder="Search Products...">

                    <div class="flex-c-m size5 ab-r-m">
                        <button id="search-clear" class="size7 color2 color0-hov trans-0-4"><i class="fs-15 fa fa-times" aria-hidden="true"></i></button>
                        <button id="search-submit" class="size7 color2 color0-hov trans-0-4"><i class="fs-15 fa fa-search" aria-hidden="true"></i></button>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-8 col-lg-9 pb-5">
            <!--  -->
            <div class="flex-sb-m flex-w pb-4">
                <div class="flex-w">
                    <div class="flex-w">
                        <p class="flex-r-m m-0 mr-2">Sort order</p>
                        <div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
                            <select class="selection-2" id="sort-selection" asp-items="ViewBag.SortOrders"></select>
                        </div>
                    </div>
                    <div class="flex-w">
                        <p class="flex-r-m m-0 mr-2">Items per page</p>
                        <div class="rs2-select2 bo4 of-hidden w-size11 m-t-5 m-b-5 m-r-10">
                            <select class="selection-2" id="page-size-selection" asp-items="ViewBag.PageSizes"></select>
                        </div>
                    </div>
                </div>
                @{ 
                    int startIndex = (Model.items.PageIndex - 1) * @Model.items.PageSize + 1;
                    int endIndex = Model.items.PageIndex * @Model.items.PageSize;
                }
                <span class="s-text8 p-t-5 p-b-5">
                    Showing @startIndex-@endIndex of @Model.items.ListCount results
                </span>
            </div>

            <!-- Product -->
            <div class="row">
                @foreach (var item in Model.items)
                {
                    <div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
                        <!-- Block2 -->
                        <div class="block2">
                            <div class="block2-img wrap-pic-w of-hidden pos-relative">
                                <img src="@((item.ImageUrl!=null)? item.ImageUrl:"/images/no-image.png")" alt="product image">

                                <div class="block2-overlay trans-0-4">
                                    <div class="block2-controls w-size1 trans-0-4">
                                        <!-- Button -->
                                        <a asp-controller="shoppingcart" asp-action="AddToShoppingCart" asp-route-itemid="@item.ItemId"
                                           class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                            Add to Cart
                                        </a>
                                        <!-- Button -->
                                        <a asp-controller="items" asp-action="details" asp-route-id="@item.ItemId"
                                           class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4 m-t-2">
                                            View details
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="block2-txt p-t-20">
                                <a asp-controller="items" asp-action="details" asp-route-id="@item.ItemId" class="block2-name dis-block s-text3 p-b-5">
                                    @item.Name
                                </a>

                                <span class="block2-price m-text6 p-r-5">
                                    $@item.Price
                                </span>
                            </div>
                        </div>
                    </div>

                }
            </div>

            <!-- Pagination -->
            <div class="pagination flex-m flex-w p-t-26">
                @for (int i = 1; i <= Model.items.TotalPages; i++)
                {
                    var active = (Model.items.PageIndex == i) ? "active-pagination" : "";
                    <button
                       data-page="@i"
                       class="item-pagination flex-c-m trans-0-4 @active">@i</button>
                }
            </div>
        </div>
    </div>
</section>
<!-- Container Selection -->
<div id="dropDownSelect1"></div>
<div id="dropDownSelect2"></div>

<!--Hidden filter form-->
<form id="filtering" asp-action="@ViewData["Title"]" method="GET">
    <input type="hidden" name="category" value="@ViewData["ActiveCategory"]" />
    <input type="hidden" name="sortOrder" value="@ViewData["CurrentSortOrder"]" />
    <input type="hidden" name="minPrice" value="@ViewData["MinPrice"]" />
    <input type="hidden" name="maxPrice" value="@ViewData["MaxPrice"]" />
    <input type="hidden" name="pageSize" value="@ViewData["PageSize"]" />
    <input type="hidden" name="page" />
    <input type="hidden" name="searchQuery" value="@ViewData["SearchQuery"]"/>

</form>

@*asp-route-category="@ViewData["ActiveCategory"]"
                       asp-route-page="@i"
                    asp-route-pageSize="@ViewData["PageSize"]"
                    asp-route-sortOrder = "@ViewData["CurrentSortOrder"]"
                    asp-route-minPrice=""*@

QualityCapsIrina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QualityCapsIrina</title>
    <base href='@Url.Content("~/")' />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/select2/css/select2.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/account.css" />
        <link rel="stylesheet" href="~/css/dropdown.css" />
        <link rel="stylesheet" href="~/css/utils.css" />
        <link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.carousel.css">
        <link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.theme.default.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
              integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
        <link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.carousel.min.css">
        <link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.theme.default.min.css">
        <link rel="stylesheet" href="~/css/utils.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/dropdown.css" asp-append-version="true" />
    </environment>
    @RenderSection("StyleSheets", required: false)
</head>
<body>
    <nav class="nav-top justify-content-between pl-lg-2 pr-lg-2">
        <div>
            <a asp-area="" asp-controller="Home" asp-action="Contact"><i class="fas fa-phone"></i> +64123456789</a>
            <a href="mailto:info@qc.co.nz"><i class="fas fa-envelope"></i> info@qc.co.nz</a>
        </div>
        <div>
            <a asp-area="" asp-controller="Home" asp-action="About">About</a>
            <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
    </nav>
    <nav class="nav-main">
        <div class="nav-block nav-categories">
            <div class="nav-item dropdown">
                <a asp-controller="items" asp-action="men" class="nav-item dropbtn">
                    Men <i class="fas fa-angle-down"></i>
                </a>
                <div class="dropdown-content">
                    @await Component.InvokeAsync("CategoriesList", new { gender = Gender.Men })
                </div>

            </div>
            <div class="nav-item dropdown">
                <a asp-controller="items" asp-action="women" class="nav-item dropbtn">
                    Women <i class="fas fa-angle-down"></i>
                </a>
                <div class="dropdown-content">
                    @await Component.InvokeAsync("CategoriesList", new { gender = Gender.Women })
                </div>
            </div>
            @*<a href="#" class="nav-item"><i class="fas fa-search"></i></a>*@
        </div>
        
        <div class="nav-block nav-logo">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo-qc.png" alt="logo" />
            </a>
        </div>
        <div class="nav-block nav-user-actions">
            @if (User.Identity.IsAuthenticated)
            {
                
                <div class="nav-item dropdown">
                    <p class="welcome pb-3 pt-3">@User.Identity.Name <i class="fas fa-angle-down"></i></p>
                    <div class="dropdown-content">
                        @if (User.IsInRole("customer"))
                        {
                            <a asp-controller="Account" asp-action="Orders"><i class="fa fa-list-ul"></i> Orders</a>
                            <a asp-controller="Account" asp-action="Profile"><i class="fa fa-user-circle"></i> Profile</a>
                        }
                        else if (User.IsInRole("admin"))
                        {
                            <a asp-area="Admin" asp-controller="Admin" asp-action="Index"><i class="fas fa-cog"></i> Admin Panel</a>
                        }
                        <hr class="m-0" />
                        <a asp-controller="Account" asp-action="LogOff"><i class="fas fa-sign-out-alt"></i> Log off</a>
                    </div>
                </div>             
            }
            else
            {
                <a asp-area="" asp-controller="Account" asp-action="Login" class="nav-item"><i class="fas fa-user"></i> Login</a>
            }

            @await Component.InvokeAsync("ShoppingCartSummary")
        </div>
    </nav>
    <div class="body-content">
        
        @RenderBody()
        
        <footer class="d-flex flex-column pl-4 pr-0 pb-4 justify-content-between">
            <div class="row w-100 d-flex">
                <div class="col-md-3 col-sm-6 mt-4">
                    <h5>Navigation</h5>
                    <div class="d-flex flex-column">
                        <a asp-area="" asp-controller="home" asp-action="index">Home</a>
                        <a asp-area="" asp-controller="items" asp-action="men">Men</a>
                        <a asp-area="" asp-controller="items" asp-action="women">Women</a>
                        <a asp-area="" asp-controller="home" asp-action="about">About</a>
                        <a asp-area="" asp-controller="home" asp-action="contact">Contact</a>
                        <a asp-area="" asp-controller="Home" asp-action="About">Profile</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 mt-4">
                    <h5>Categories</h5>
                    <div class="d-flex flex-column">
                        <a asp-area="" asp-controller="home" asp-action="index">Peruvian</a>
                        <a asp-area="" asp-controller="items" asp-action="men">Flat</a>
                        <a asp-area="" asp-controller="items" asp-action="women">Basketball</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 mt-4 ">
                    <h5>Contact us</h5>
                    <div class="d-flex flex-column">
                        <div><i class="fas fa-phone"></i> +64123456789</div>
                        <div><i class="mr-1 fas fa-location-arrow"></i> 75 Queen Street, Auckland</div>
                    </div>
                    <h5 class="mt-4">Social</h5>
                    <div class="d-flex social">
                        <a href="#"><i class="mr-1 fab fa-facebook-square hover-orangebrown"></i></a>
                        <a href="#"><i class="mr-1 fab fa-twitter-square hover-orangebrown"></i></a>
                        <a href="#"><i class="mr-1 fab fa-instagram hover-orangebrown"></i></a>
                    </div>

                </div>

                <div class="col-md-3 col-sm-6 mt-4 d-flex flex-column justify-content-between">
                    <div class="mb-4">
                        <h5>Payment methods</h5>
                        <div class="d-flex" style="font-size: 30px;">
                            <i class="mr-1 fab fa-cc-visa"></i>
                            <i class="mr-1 fab fa-cc-mastercard"></i>
                            <i class="mr-1 fab fa-cc-paypal"></i>
                        </div>
                    </div>
                    <div><p>2018 - Quality Caps. Belovolov 1484314</p></div>
                </div>
            </div>
            
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="~/lib/popper.js/umd/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/fontawesome-free-5.0.10/svg-with-js/js/fontawesome-all.js"></script>
        <script src="~/lib/owl.carousel/owl.carousel.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/lib/select2/js/select2.js"></script>
        <script src="~/js/latest-arrivals.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="~/lib/popper.js/umd/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/fontawesome-free-5.0.10/svg-with-js/js/fontawesome-all.js"></script>
        <script src="~/lib/owl.carousel/owl.carousel.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/lib/select2/js/select2.js"></script>
        <script src="~/js/latest-arrivals.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>